Moveideas
NinaBusz/Ideas pull request #13
Opened 2023-04-11 08:03 UTC by NinaBusz

good morning 👋 

added:
- an (hidden) area to each idea that is opening via a button "verschieben" (you can pick a specific project there and assign the idea)
- list for each project-detail-page to show the assigned ideas
- button to delete the ideas in the project-detail-page

also:
- refactoring (added new component)
- styling just for test purposes(styled components will follow this week)

2023-04-11 09:10 UTC, PReichetanz requested changes
Really nice work! I left some comments to discuss some details which might be useful 🚀

2023-04-11 09:10 UTC, PReichetanz commented on components/Idea/Idea.js
> +          className="primaryButton__delete"
Refactoring to styled components will be harder with each line of code you add, so make sure to refactor as soon as possible.

2023-04-11 09:10 UTC, PReichetanz commented on components/Idea/Idea.js
> +        </button>
Since this is not a form submit button, you should add the correct `type="button"` attribute.

2023-04-11 09:10 UTC, PReichetanz commented on components/Idea/Idea.js
> +      ) : null}
You don't need the ternary operator if you just want to render nothing if the condition is not met:
```suggestion
      {isMovingIdea[id] && (
        <IdeasMoveArea
          projects={projects}
          selectedProjectForIdea={selectedProjectForIdea}
          handleSelectedProjectForIdea={handleSelectedProjectForIdea}
          handleAddIdeaToProject={handleAddIdeaToProject}
        />
      )}
```

2023-04-11 09:10 UTC, PReichetanz commented on components/IdeasForm/index.js
> +          </button>
I think the first one is not the submit button, but the second one is, right? Currently, the submit event should also be fired if you click "Idee verwerfen" because the button is `type="submit"` by default.

2023-04-11 09:10 UTC, PReichetanz commented on components/IdeasForm/index.js
>      </>
You don't need this fragment because the `form` can be your parent element.

2023-04-11 09:10 UTC, PReichetanz commented on components/IdeasList/index.js
>      <>
```suggestion
```

2023-04-11 09:10 UTC, PReichetanz commented on components/IdeasList/index.js
>        <ul className="ideasList">
You've set `list-style="none"`, so please add `role="list"` to [ensure a11y in Safari as well](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style#accessibility_concerns).

2023-04-11 09:10 UTC, PReichetanz commented on components/IdeasMoveArea/index.js
> +      <ul>
```suggestion
      <ul role="list">
```

2023-04-11 09:10 UTC, PReichetanz commented on components/IdeasMoveArea/index.js
> +      <p>Welchem Projekt möchtest du die Idee zuordnen?</p>
This feels rather like a heading instead of the simple paragraph.

2023-04-11 09:10 UTC, PReichetanz commented on components/IdeasMoveArea/index.js
> +        ))}
The `onClick` should be placed on a `button` element because the `li` is not clickable by default (it's an a11y issue: the screen reader will not tell the user that the following content is clickable):
```suggestion
          <li
            key={project.id}
          >
          <button type="button" onClick={() => handleSelectedProjectForIdea(project.id)} >
            <article className="moveArea">
              {selectedProjectForIdea === project.id && (
                <span className="selected">-X|</span>
              )}
              <p>{project.title}</p>
              {selectedProjectForIdea === project.id && (
                <span className="selected">|X-</span>
              )}
            </article>
            </button>
          </li>
        ))}
```

2023-04-11 09:10 UTC, PReichetanz commented on components/ProjectForm/index.js
> +      <form>
The form should have a heading (at least for the screen reader if not visible to the user).

2023-04-11 09:10 UTC, PReichetanz commented on components/ProjectForm/index.js
> +        <section className="projectsarea__formLayout">
Do you need this `section` only for styling? If so, you could pass the styling to the `form` and remove the `section`.

2023-04-11 09:10 UTC, PReichetanz commented on components/ProjectForm/index.js
> +          <label htmlFor="project__image">Projektbild:</label>
This label is not associated with an input / textarea, because there is no element with the id `project__image`.

2023-04-11 09:10 UTC, PReichetanz commented on components/ProjectForm/index.js
> +          <label htmlFor="project__name">Projektname:</label>
Please check the connection between label and textarea via `htmlFor`.

2023-04-11 09:10 UTC, PReichetanz commented on components/ProjectForm/index.js
> +          <label htmlFor="project__description">Beschreibung:</label>
Please check the connection between label and textarea via `htmlFor`.

2023-04-11 09:10 UTC, PReichetanz commented on components/ProjectForm/index.js
> +        </button>
Is deleting the project actually the same as submitting the form? I would have expected the first button to be from type "button" and the second one to be a submit button.

2023-04-11 09:10 UTC, PReichetanz commented on pages/ideasPage/index.js
> +export default function IdeasPage({ projects, setProjects }) {
Passing the `setProjects` as prop is confusing because inside the `IdeasPage`, it's not clear which setter function belongs to a state inside of this component (like `setIdeas`) and which one comes from above (like `setProjects`).

I would suggest to, in the component where `setProjects` lives, wrap`setProjects` in a `handleProjects` function and pass it as `onHandleProjects` (or similar) to this `IdeasPage`. 

You have already done the same thing inside of this component with all state handler functions you pass down to other components.

2023-04-11 09:10 UTC, PReichetanz commented on pages/ideasPage/index.js
>      <article className="ideasList">
Do you really need this article?

2023-04-11 09:10 UTC, PReichetanz commented on pages/projects/[id].js
> +            setFoundProject={setFoundProject}
This is another case where we would suggest to pass a `handleFoundProject` instead of the setter function directly.

2023-04-11 09:10 UTC, PReichetanz commented on pages/projects/[id].js
> +            <ul>
```suggestion
            <ul role="list">
```

2023-04-11 09:10 UTC, PReichetanz commented on pages/projects/[id].js
> +              <p>Ideenliste</p>
This should rather be a heading, but it [needs to be outside of the `ul`](https://caninclude.glitch.me/caninclude?child=p&parent=ul).

2023-04-11 09:10 UTC, PReichetanz commented on pages/projects/[id].js
> +                      </button>
Please specify the type of this button.

2023-04-11 09:10 UTC, PReichetanz commented on pages/projects/index.js
> +                      : "http://localhost:3001/_next/image?url=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1679345506039-c4228a79c93a%3Fixlib%3Drb-4.0.3%26ixid%3DMnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB
I think that this will not work as soon as you deploy to vercel. You could add a "normal" URL without the `localhost` part for a default image, I guess.

2023-04-11 09:10 UTC, PReichetanz commented on styles.js
> +  word-break: break-word}
Looks like the pretter extension is not working on save; please check your VSCode settings.

2023-04-11 13:56 UTC, NinaBusz commented on styles.js
> +  word-break: break-word}
Thank you for the detailed check on my code! 😃 I tried to solve all issues. Only prettier is still not working as expected in the styles.js (only there idk why)

2023-04-11 16:25 UTC, Satttoshi commented
LGTM :rocket:

2023-04-12 06:53 UTC, NinaBusz commented
> LGTM 🚀

Thank you for the check! 🙏

2023-04-12 06:53 UTC, merged